### ISSUE TITLE
No module named 'poloniex'

### ISSUE THREAD

**Issue by xucongyong** [Aula13/poloniex#12]
environment：python3.6

```shell
>>> from poloniex import Poloniex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'poloniex'
```

**Comment by dnlcrl** [comment]
wtf dude, have you even tried installing it? lol

**Comment by xucongyong** [comment]
environment：python3

pip3 install poloniex

**Comment by dnlcrl** [comment]
Ok given the additional info you provided (you tried to install it 🥇 ) I reopen the issue, we will check asap

**Comment by enricobacis** [comment]
I was trying to reproduce it (or actually to demonstrate it didn't), and apparently something fishy is going on. Check this: https://asciinema.org/a/ndtJB90TdJ4bZ1gMwz7VoO3Pj

We will investigate more

**Comment by enricobacis** [comment]
It turned out that _asciinema_ (the tool I was using to record the screen was setting my `$PYTHONPATH`, which messes up with virtualenv. this is hysterical 😄 

I confirm poloniex is working correctly even on python 3.6. Check out the video here: http://www.giphy.com/gifs/xULW8vvgQbAryzQmn6

**Take away message**: be sure about the content of your `$PYTHONPATH` variable, and be sure that you are installing  in the correct place (`which pip3`, `which python3`, etc.), poloniex itself is working fine.
